0x0C:
  xyz.openbmc_project.Inventory.Decorator.Operational:
    State:
      0x04:
        assert: ''"Disabled"''
        dassert: ''"Enabled"''
0x07:
  xyz.openbmc_project.Inventory.Item:
    Present:
      0x07:
        assert: '"true"'
        dassert: '"false"'
